export interface Course {
  id: number;
  title: string;
  instructor: string;
  thumbnail: string;
  rating: number;
  reviewCount: number;
  price: number;
  duration: number; // 시간 단위
  level: '입문' | '초급' | '중급' | '고급';
  category: string;
  subCategory: string;
  badge?: 'NEW' | '인기';
}

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: '[2026 최신판] 정보처리기사 실기 완전정복',
    instructor: '김정보',
    thumbnail: '/mock/course1.jpg',
    rating: 4.9,
    reviewCount: 10234,
    price: 12900,
    duration: 42,
    level: '초급',
    category: '건강·자격증',
    subCategory: '정보처리기사',
    badge: '인기',
  },
  {
    id: 2,
    title: '빅데이터분석기사 실기 합격 전략',
    instructor: '박데이터',
    thumbnail: '/mock/course2.jpg',
    rating: 4.8,
    reviewCount: 5432,
    price: 14900,
    duration: 28,
    level: '중급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
    badge: 'NEW',
  },
  {
    id: 3,
    title: 'SQL 개발자 자격증 한번에 따기',
    instructor: '이쿼리',
    thumbnail: '/mock/course3.jpg',
    rating: 4.7,
    reviewCount: 12347,
    price: 9900,
    duration: 18,
    level: '초급',
    category: '건강·자격증',
    subCategory: 'SQL개발자',
  },
  {
    id: 4,
    title: '정보보안기사 이론+실습 올인원',
    instructor: '최보안',
    thumbnail: '/mock/course4.jpg',
    rating: 4.9,
    reviewCount: 9876,
    price: 15900,
    duration: 55,
    level: '중급',
    category: '건강·자격증',
    subCategory: '정보보안기사',
  },
  {
    id: 5,
    title: '데이터분석준전문가(ADsP) 단기 합격',
    instructor: '정분석',
    thumbnail: '/mock/course5.jpg',
    rating: 4.8,
    reviewCount: 11234,
    price: 8900,
    duration: 22,
    level: '입문',
    category: '건강·자격증',
    subCategory: '데이터분석준전문가',
    badge: 'NEW',
  },
  {
    id: 6,
    title: '정보처리기사 실기 프로젝트 완성',
    instructor: '공준비',
    thumbnail: '/mock/course6.jpg',
    rating: 4.6,
    reviewCount: 7654,
    price: 11900,
    duration: 35,
    level: '중급',
    category: '건강·자격증',
    subCategory: '정보처리기사',
  },
  {
    id: 7,
    title: 'SQL 개발자 기출문제 완벽 분석',
    instructor: '유시디',
    thumbnail: '/mock/course7.jpg',
    rating: 4.6,
    reviewCount: 7854,
    price: 7900,
    duration: 15,
    level: '초급',
    category: '건강·자격증',
    subCategory: 'SQL개발자',
  },
  {
    id: 8,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 9,
    title: 'AI 이미지 생성 완전정복',
    instructor: '김에이아이',
    thumbnail: '/mock/course9.jpg',
    rating: 4.8,
    reviewCount: 8321,
    price: 13900,
    duration: 24,
    level: '입문',
    category: 'AI·데이터',
    subCategory: 'AI 디자인·이미지',
    badge: 'NEW',
  },
  {
    id: 10,
    title: '업무 자동화 with Python',
    instructor: '이자동',
    thumbnail: '/mock/course10.jpg',
    rating: 4.7,
    reviewCount: 6543,
    price: 11900,
    duration: 30,
    level: '초급',
    category: 'AI·데이터',
    subCategory: '업무생산성·자동화',
  },
  {
    id: 11,
    title: 'ChatGPT로 수익화하는 법',
    instructor: '박수익',
    thumbnail: '/mock/course11.jpg',
    rating: 4.5,
    reviewCount: 4321,
    price: 9900,
    duration: 12,
    level: '입문',
    category: 'AI·데이터',
    subCategory: 'AI 수익화',
    badge: '인기',
  },
  {
    id: 12,
    title: 'AI 영상편집 마스터클래스',
    instructor: '최영상',
    thumbnail: '/mock/course12.jpg',
    rating: 4.6,
    reviewCount: 5678,
    price: 16900,
    duration: 40,
    level: '중급',
    category: 'AI·데이터',
    subCategory: 'AI 영상·사운드',
  },
  {
    id: 13,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 14,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 15,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 16,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 17,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 18,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 19,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 20,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
  {
    id: 21,
    title: '빅데이터분석기사 필기+실기 종합반',
    instructor: '빅데이터팀',
    thumbnail: '/mock/course8.jpg',
    rating: 4.9,
    reviewCount: 10967,
    price: 17900,
    duration: 68,
    level: '고급',
    category: '건강·자격증',
    subCategory: '빅데이터분석기사',
  },
];